-- =============================================
-- Performance Optimization - Indexes
-- =============================================

USE [XTRACHEF_DB]
GO

-- Index on STATUS for fast filtering
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[MTS_EMAILMASTER]') AND name = N'IX_MTS_EMAILMASTER_STATUS_REQUESTTIME')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_MTS_EMAILMASTER_STATUS_REQUESTTIME]
    ON [dbo].[MTS_EMAILMASTER] ([STATUS], [REQUESTTIME])
    INCLUDE ([TEMPLATEID], [EMAILSP], [CORRELATION_ID])
    PRINT 'Index IX_MTS_EMAILMASTER_STATUS_REQUESTTIME created'
END
GO

-- Index on TEMPLATEID for template-based queries
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[MTS_EMAILMASTER]') AND name = N'IX_MTS_EMAILMASTER_TEMPLATEID_STATUS')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_MTS_EMAILMASTER_TEMPLATEID_STATUS]
    ON [dbo].[MTS_EMAILMASTER] ([TEMPLATEID], [STATUS])
    INCLUDE ([REQUESTTIME])
    PRINT 'Index IX_MTS_EMAILMASTER_TEMPLATEID_STATUS created'
END
GO

-- Index on CORRELATION_ID for tracking
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[MTS_EMAILMASTER]') AND name = N'IX_MTS_EMAILMASTER_CORRELATION_ID')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_MTS_EMAILMASTER_CORRELATION_ID]
    ON [dbo].[MTS_EMAILMASTER] ([CORRELATION_ID])
    WHERE CORRELATION_ID IS NOT NULL
    PRINT 'Index IX_MTS_EMAILMASTER_CORRELATION_ID created'
END
GO

-- Index on SERVICENAME for service queries
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[MTS_SERVICECONFIG]') AND name = N'IX_MTS_SERVICECONFIG_SERVICENAME')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_MTS_SERVICECONFIG_SERVICENAME]
    ON [dbo].[MTS_SERVICECONFIG] ([SERVICENAME])
    INCLUDE ([STATUS], [LAST_RUN])
    PRINT 'Index IX_MTS_SERVICECONFIG_SERVICENAME created'
END
GO

PRINT 'Performance indexes created successfully!'
GO
